### ISSUE TITLE
Hang due to infinite loop when using EFI Stub

### ISSUE THREAD

**Issue by concatime** [cloud-hypervisor/rust-hypervisor-firmware#104] opened 2021-04-01 04:47 UTC
Hi. When I use [this image](https://mega.nz/file/W45SlCRQ#Fv0OHQLZrhEbxYPpeObiY8tkHu-BuT6k4KGS-nbANcA), hypervisor-fm hangs at:
https://github.com/cloud-hypervisor/rust-hypervisor-firmware/blob/0.3.0/src/main.rs#L132

I tried to debug, and realized that this loop does not exit (section_bytes_remaining=32, page_rva=0, block_size=0):
https://github.com/cloud-hypervisor/rust-hypervisor-firmware/blob/0.3.0/src/pe.rs#L193

I think it is related to FAT. Can you take a look?

(cloud-hypervisor v0.14.1 & rust-hypervisor-firmware 0.3.0)

Thank you.

**Comment by retrage** [comment] 2021-04-01 07:58
Hi,

The Linux boot image uses [EFI Stub](https://www.kernel.org/doc/Documentation/efi-stub.txt), which adds PE/COFF header to the Linux kernel image so that it can be loaded and boot from EFI without a bootloader like GRUB. Unfortunately, booting with EFI Stub is not tested yet because the primary target is Ubuntu (with shim + GRUB). However, it would be nice to support EFI Stub.

I think this is not related FAT filesystem but the PE loader.
As you mentioned, the hang is caused in the PE loader relocation process.
```rust
                    let page_rva = reloc_region.read_u32(offset);
                    let block_size = reloc_region.read_u32(offset + 4);
```
The `page_rva` and `block_size` are Page RVA and Block Size in the base relocation block[1].
Because these values are used to calculate the relocation information, they should be non-zero values.
This case should be handled correctly to avoid the hang.
Anyway, I tried the following workaround to ignore the invalid base relocation block. It does not hang and the image is loaded, but the system is crashed immediately. There are other issues to boot EFI Stub.
```patch
diff --git a/src/pe.rs b/src/pe.rs
index 05ab6bd..51f3846 100644
--- a/src/pe.rs
+++ b/src/pe.rs
@@ -194,6 +194,11 @@ impl<'a> Loader<'a> {
                     // Read details for block
                     let page_rva = reloc_region.read_u32(offset);
                     let block_size = reloc_region.read_u32(offset + 4);
+                    if block_size == 0 {
+                        let block_size = 8;
+                        section_bytes_remaining -= block_size;
+                        offset += u64::from(block_size);
+                    }
                     let mut block_offset = 8;
                     while block_offset < block_size {
                         let entry = reloc_region.read_u16(offset + u64::from(block_offset));
```


* [1] https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#the-reloc-section-image-only

**Comment by concatime** [comment] 2021-04-01 14:30
I see. Thank you. And yes, support for EFI Stub would be awesome (no need tor GRUB or systemd-boot)!

**Comment by rbradford** [comment] 2021-04-01 16:47
The issue is due to us simply skipping copying over the relocation table into the guest memory because our code only handles sector aligned values:https://github.com/cloud-hypervisor/rust-hypervisor-firmware/blob/master/src/pe.rs#L151

Because the relocation isn't copied over from the file into the memory the memory is zero. However you've pointed out that the Linux kernel doesn't need a relocation table we can safely skip it.

**Comment by rbradford** [comment] 2021-04-01 16:48
```diff
diff --git a/src/pe.rs b/src/pe.rs
index 05ab6bd..cfd4892 100644
--- a/src/pe.rs
+++ b/src/pe.rs
@@ -182,6 +182,11 @@ impl<'a> Loader<'a> {
 
         for section in sections {
             if &section.name[0..6] == b".reloc" {
+                // This matches the skipped copy above
+                if section.raw_offset % 512 != 0 {
+                    continue;
+                }
+
                 let section_size = core::cmp::min(section.raw_size, section.virt_size);
                 let l: &mut [u8] = loaded_region
                     .as_mut_slice(u64::from(section.virt_address), u64::from(section_size));

```

**Comment by rbradford** [comment] 2021-04-01 16:50
The correct fix is to support copying non-sector aligned data from a file into memory. However in practice all the PE binaries i've seen either have a proper relocation table which is sector aligned (and quite large) or have only the fake one like CONFIG_EFI_STUB so we could go with a change like the one above to avoid this infinite loop.

**Comment by retrage** [comment] 2021-04-02 08:41
Thanks. I think so. The above your patch is reasonable and works better than mine.

**Comment by retrage** [comment] 2021-04-02 08:43
Also, this is somehow off-topic, but the EFI Stub needs kernel parameters via EFI load options. Here is a quick trial:

```patch
diff --git a/src/efi/mod.rs b/src/efi/mod.rs
index deda718..d6b204a 100644
--- a/src/efi/mod.rs
+++ b/src/efi/mod.rs
@@ -913,6 +913,18 @@ fn new_image_handle(
 
     crate::common::ascii_to_ucs2(path, &mut file_paths[0].filename);
 
+    const EFI_STUB_OPTIONS: &str = "/EFI/BOOT/BOOTX64.EFI earlyprintk=serial";
+    let mut load_options = null_mut();
+    let status = allocate_pool(
+        MemoryType::LoaderData,
+        size_of::<[u16; 512]>(),
+        &mut load_options as *mut *mut c_void,
+    );
+    assert!(status == Status::SUCCESS);
+    let load_options = unsafe { &mut *(load_options as *mut [u16; 512]) };
+    crate::common::ascii_to_ucs2(EFI_STUB_OPTIONS, load_options);
+    let load_options_size = (crate::common::ascii_length(EFI_STUB_OPTIONS)  + 1) * size_of::<u16>();
+
     let mut image = null_mut();
     allocate_pool(
         MemoryType::LoaderData,
@@ -931,8 +943,8 @@ fn new_image_handle(
             system_table: unsafe { &mut ST },
             device_handle,
             file_path: &mut file_paths[0].device_path, // Pointer to first path entry
-            load_options_size: 0,
-            load_options: null_mut(),
+            load_options_size: load_options_size as u32,
+            load_options: load_options as *mut _ as *mut c_void,
             image_base: load_addr as *mut _,
             image_size: load_size,
             image_code_type: efi::MemoryType::LoaderCode,
```

**Comment by rbradford** [comment] 2021-04-06 09:32
If you're going to use Linux `CONFIG_EFI_STUB` with rust-hypervisor-firmware then you should look at `CONFIG_CMDLINE` or `CONFIG_CMDLINE_OVERRIDE`

**Comment by retrage** [comment] 2022-06-11 03:12
It looks like the reported bug is fixed. We can close this issue.

**Closed** 2022-06-13 09:35 UTC
